const TripList = [
  {
    id: 0,
    type: "Ongoing Trips",
    data: [
      {
        id: 0,
        CarName: "Toyota Corolla ",
        bookingId: "LF123456783",
        price: "$ 2000",
        status: "Ongoing",
        payment: "Partial Payment done",
        pickUpDate: "12 Feb, 10:00 AM",
        DropDate: "3 Feb, 10:00 AM",
        ReturnLocation: "Anna Nagar, !st Avenue, Chennai, Tamil Nadu, 600040",
      },
    ],
  },
  {
    id: 1,
    type: "Upcoming Trips",
    data: [
      {
        id: 0,
        CarName: "Toyota Corolla ",
        bookingId: "LF923456789",
        price: "$ 2000",
        status: "Accepted",
        payment: "Partial Payment done",
        pickUpDate: "12 Feb, 10:00 AM",
        DropDate: "3 Feb, 10:00 AM",
        ReturnLocation: "Anna Nagar, !st Avenue, Chennai, Tamil Nadu, 600040",
      },
      {
        id: 1,
        CarName: "BMW 2023",
        bookingId: "LF123056749",
        price: "$ 2000",
        status: "Requested",
        payment: "Partial Payment done",
        pickUpDate: "12 Feb, 10:00 AM",
        DropDate: "3 Feb, 10:00 AM",
        ReturnLocation: "Anna Nagar, !st Avenue, Chennai, Tamil Nadu, 600040",
      },
      {
        id: 2,
        CarName: "AUDI ",
        bookingId: "LF123453789",
        price: "$ 2000",
        status: "Accepted",
        payment: "Partial Payment done",
        pickUpDate: "12 Feb, 10:00 AM",
        DropDate: "3 Feb, 10:00 AM",
        ReturnLocation: "Anna Nagar, !st Avenue, Chennai, Tamil Nadu, 600040",
      },
    ],
  },
  {
    id: 2,
    type: "Past Trips",
    data: [
      {
        id: 0,
        CarName: "Toyota Corolla ",
        bookingId: "LF123256789",
        price: "$ 2000",
        status: "Cancelled",
        payment: "Partial Payment done",
        pickUpDate: "12 Feb, 10:00 AM",
        DropDate: "3 Feb, 10:00 AM",
      },
      {
        id: 1,
        CarName: "BMW 2023",
        bookingId: "L5123456789",
        price: "$ 2000",
        status: "Completed",
        payment: "Partial Payment done",
        pickUpDate: "12 Feb, 10:00 AM",
        DropDate: "3 Feb, 10:00 AM",
      },
      {
        id: 2,
        CarName: "AUDI ",
        bookingId: "LF129456789",
        price: "$ 2000",
        status: "Completed",
        payment: "Partial Payment done",
        pickUpDate: "12 Feb, 10:00 AM",
        DropDate: "3 Feb, 10:00 AM",
      },
    ],
  },
];
export default TripList;
